In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url ='https://tw.stock.yahoo.com/rank/volume?exchange=TAI'

In [4]:
print(url)

https://tw.stock.yahoo.com/rank/volume?exchange=TAI

In [5]:
response = requests.get(url)

In [ ]:
if response.status_code == 200:
  soup = BeautifulSoup(response.text, 'html.parser')

In [ ]:
for x in soup.find_all('li', class_='List(n)'):
  print(x.text.strip()," ")

1元大台灣價值高息00940.TW9.530.292.95%9.779.530.24659,60563.3610
2元大台灣50反100632R.TW3.990.123.10%4.013.910.10443,08017.5619
3復華台灣科技優息00929.TW20.300.552.64%20.6420.300.34348,05470.9801
4群益台灣精選高息00919.TW24.540.682.70%25.0524.500.55263,47365.0125
5大亞1609.TW53.602.003.60%57.4053.603.80230,673127.7543
6鴻海2317.TW141.005.003.42%143.00137.505.50175,093245.1813
7國泰永續高股息00878.TW22.000.512.27%22.4021.920.48155,62734.3691
8大同2371.TW58.502.904.72%60.8057.803.00145,76286.1860
9統一台灣高息動能00939.TW14.280.422.86%14.6214.260.36137,23219.6979
10三商壽2867.TW6.140.264.42%6.405.720.68129,8957.8905
11元大高股息0056.TW38.491.132.85%39.1538.270.88116,35944.9526
12緯創3231.TW114.005.504.60%118.50112.506.0097,161111.6797
13群創3481.TW13.650.453.19%14.0513.550.5089,96112.3286
14長榮航2618.TW31.000.702.21%31.7030.950.7589,74327.9859
15聯電2303.TW50.101.502.91%51.0050.100.9085,23442.9960
16開發金2883.TW13.250.402.93%13.6013.100.5084,97511.3160
17合機1618.TW48.300.952.01%51.0048.102.9082,62940.7486
18中興電1513.TW190.5012.506.16%201.00189.0012.0076,276147.7305
19元大滬深300正200637L.TW13.550.080.59%13.5613.250.3172,9359.7923
20富邦恒生國企正200665L.TW5.580.152.62%5.665.520.1470,9613.9593
21元大美債20正200680L.TW8.010.172.08%8.067.990.0767,2075.3898
22中信金2891.TW30.951.003.13%32.0530.901.1566,13920.6684
23宏碁2353.TW45.502.054.31%47.5045.002.5062,58628.7436
24中工2515.TW15.150.704.42%15.7514.900.8559,0868.9700
25華邦電2344.TW25.501.154.32%26.5025.301.2059,06715.2503
26亞航2630.TW43.700.902.02%47.6041.506.1056,25425.4160
27燿華2367.TW26.401.806.38%27.9526.001.9555,33714.7699
28新光金2888.TW8.050.141.71%8.188.030.1552,1194.2103
29漢翔2634.TW55.402.604.48%59.8054.305.5051,16028.9552
30玉山金2884.TW26.300.752.77%27.0026.200.8050,86913.4956
31台積電2330.TW788.0018.002.23%803.00785.0018.0049,412391.1173
32華榮1608.TW36.802.205.64%39.7036.802.9048,64618.3738
33華新1605.TW38.051.553.91%40.0037.852.1548,24018.7340
34廣達2382.TW249.5011.504.41%261.50248.0013.5046,395117.0867
35英業達2356.TW53.902.103.75%55.9053.302.6045,37424.6270
36中信上游半導體00941.TW15.100.150.98%15.1915.060.1344,7756.7586
37友達2409.TW17.600.301.68%17.9017.450.4542,6957.5333
38台泥1101.TW32.450.100.31%33.3032.400.9042,49113.9388
39復華香港正200650L.TW8.430.273.10%8.588.370.2142,2343.5748
40光寶科2301.TW95.306.706.57%101.0094.106.9039,05437.8512
41大華優利高填息3000918.TW22.870.552.35%23.2122.670.5436,8848.4384
42復華富時不動產00712.TW9.300.090.96%9.319.280.0336,8063.4215
43台新金2887.TW17.400.452.52%17.8517.400.4536,5446.4167
44矽統2363.TW63.001.001.61%63.5059.404.1036,31422.3510
45長榮2603.TW170.507.504.21%177.50170.007.5036,21362.4464
46臺企銀2834.TW15.800.251.56%16.0515.800.2535,8875.6947
47群益半導體收益00927.TW19.020.613.11%19.4118.950.4634,8856.6742
48國泰金2882.TW47.851.102.25%48.8047.551.2534,22716.4394
49富邦越南00885.TW11.900.604.80%12.1011.860.2434,1924.0932
50中信中國50正200753L.TW6.650.202.92%6.766.600.1633,1802.2154
51第一銅2009.TW51.200.500.99%54.3050.204.1031,84916.7767
52國泰20年美債正200688L.TW7.960.172.09%8.017.940.0731,0992.4781
53佳能2374.TW38.450.802.12%39.9036.303.6030,92711.8124
54仁寶2324.TW35.301.002.75%36.3034.901.4029,76010.5934
55第一金2892.TW26.750.451.65%27.2026.750.4529,6987.9890
56東元1504.TW56.302.904.90%58.8056.302.5028,36916.2302
57兆豐金2886.TW39.100.701.76%40.0539.100.9528,12811.0878
58陽明2609.TW43.801.403.10%45.1543.551.6027,84912.2698
59誠美材4960.TW12.350.705.36%13.0011.751.2526,7453.2282
60國泰臺灣加權反100664R.TW4.510.122.73%4.544.430.1126,7141.1957
61力積電6770.TW24.150.853.40%24.8524.000.8526,4206.3970
62華航2610.TW19.250.552.78%19.8019.250.5526,2095.0909
63南亞科2408.TW65.504.506.43%69.3064.604.7026,18517.4088
64永豐金2890.TW21.250.552.52%21.9021.150.7525,7615.5078
65神達3706.TW44.552.304.91%46.8044.402.4025,71811.6234
66彰銀2801.TW17.800.351.93%18.1017.750.3525,4314.5448
67富邦金2881.TW65.701.702.52%67.2065.601.6025,06316.5836
68和成1810.TW20.901.9010.00%20.9020.200.7024,8585.1715
69一詮2486.TW69.901.902.65%71.5067.803.7024,72417.1343
70中鋼2002.TW24.250.301.22%24.5024.200.3024,5085.9512
71宏泰1612.TW36.952.055.26%39.3536.602.7524,3169.1254
72元大金2885.TW29.950.601.96%30.5029.800.7023,4947.0518
73泰金寶-DR9105.TW3.500.154.11%3.643.480.1623,2320.8208
74國泰台灣5G+00881.TW20.650.643.01%21.0220.460.5622,1524.5815
75華通2313.TW76.603.103.89%79.0076.302.7021,76416.8224
76富邦特選高股息3000900.TW15.360.432.72%15.6815.250.4321,6323.3256
77日月光投控3711.TW153.007.004.38%158.50152.506.0021,43233.0567
78華泰2329.TW63.804.907.13%68.8063.305.5021,37314.0499
79期元大S&P日圓正200706L.TW6.420.050.77%6.446.410.0321,0541.3524
80寶成9904.TW34.002.206.08%35.5033.851.6520,8577.1761
81中信關鍵半導體00891.TW17.460.543.00%17.8017.360.4420,6973.6225
82京元電子2449.TW99.704.804.59%103.5098.604.9020,53820.6037
83弘憶股3312.TW44.754.559.23%49.0044.404.6020,4849.4300
84中石化1314.TW9.410.252.59%9.699.370.3220,3581.9250
85華南金2880.TW22.400.552.40%22.9022.350.5520,1784.5470
86王道銀行2897.TW9.860.242.38%10.109.860.2420,1502.0024
87國建2501.TW27.550.602.13%28.8527.251.6020,1005.6278
88盛達3027.TW46.250.300.64%48.1044.803.3020,0499.3871
89合庫金5880.TW25.700.401.53%26.1025.700.4019,8925.1341
90富邦NASDAQ反100671R.TW4.180.092.20%4.194.160.0319,4160.8102
91中信成長高股息00934.TW18.460.492.59%18.7618.330.4319,0733.5240
92士電1503.TW307.002.000.65%322.50297.0025.5018,93159.0672
93凌陽2401.TW29.301.505.40%29.4027.851.5518,9085.4346
94國泰台灣領袖5000922.TW18.580.552.88%18.9918.470.5218,9053.5302
95淳安6283.TW34.202.708.57%34.6531.952.7018,8036.2852
96和碩4938.TW95.403.303.34%98.5095.003.5018,58017.8962
97榮星1617.TW22.551.808.67%22.8021.401.4018,0844.0488
98晟銘電3013.TW69.602.403.33%71.7067.004.7017,68312.1767
99群益證6005.TW21.050.552.55%21.6020.750.8517,6703.7197
100南港2101.TW46.201.152.43%47.0545.201.8517,1337.8574

In [ ]:
# 建立空陣列

num = []
price = []
up_down = []
Quote_change = []
Highest = []
lowest = []
price_gap = []
Trading_volume = []
Transaction_amount = []


data = {
    "股名股號": num,
    "股價": price,
    "漲跌": up_down,
    "漲跌幅": Quote_change,
    "最高": Highest,
    "最低": lowest,
    "價差": price_gap,
    "成交量": Trading_volume,
    "成交金額": Transaction_amount
}

In [ ]:
i=0
for x in soup.find_all('div', class_='D(f) Ai(c)'):   #股號/股名
  if i!=0:
    num.append(x.text.strip())
  i+=1
print(num)
print(len(num))

['00940.TW', '00632R.TW', '00929.TW', '00919.TW', '1609.TW', '2317.TW', '00878.TW', '2371.TW', '00939.TW', '2867.TW', '0056.TW', '3231.TW', '3481.TW', '2618.TW', '2303.TW', '2883.TW', '1618.TW', '1513.TW', '00637L.TW', '00665L.TW', '00680L.TW', '2891.TW', '2353.TW', '2515.TW', '2344.TW', '2630.TW', '2367.TW', '2888.TW', '2634.TW', '2884.TW', '2330.TW', '1608.TW', '1605.TW', '2382.TW', '2356.TW', '00941.TW', '2409.TW', '1101.TW', '00650L.TW', '2301.TW', '00918.TW', '00712.TW', '2887.TW', '2363.TW', '2603.TW', '2834.TW', '00927.TW', '2882.TW', '00885.TW', '00753L.TW', '2009.TW', '00688L.TW', '2374.TW', '2324.TW', '2892.TW', '1504.TW', '2886.TW', '2609.TW', '4960.TW', '00664R.TW', '6770.TW', '2610.TW', '2408.TW', '2890.TW', '3706.TW', '2801.TW', '2881.TW', '1810.TW', '2486.TW', '2002.TW', '1612.TW', '2885.TW', '9105.TW', '00881.TW', '2313.TW', '00900.TW', '3711.TW', '2329.TW', '00706L.TW', '9904.TW', '00891.TW', '2449.TW', '3312.TW', '1314.TW', '2880.TW', '2897.TW', '2501.TW', '3027.TW', '5880.TW', '00671R.TW', '00934.TW', '1503.TW', '2401.TW', '00922.TW', '6283.TW', '4938.TW', '1617.TW', '3013.TW', '6005.TW', '2101.TW']
100

In [ ]:

# 使用列表形式傳遞多個類別名稱
for x in soup.find_all('span', class_=['Jc(fe) Fw(600) D(f) Ai(c) C($c-trend-up)', 'Jc(fe) Fw(600) D(f) Ai(c) C($c-trend-down)', 'Jc(fe) Fw(600) C(#fff) Px(6px) Py(2px) Bdrs(4px) Bgc($c-trend-up)','Jc(fe) Fw(600) D(f) Ai(c)']):   #股價
    price.append(x.text.strip())

print(price)
print(len(price))


#Jc(fe) Fw(600) D(f) Ai(c) C($c-trend-up) 正常紅色
#Jc(fe) Fw(600) D(f) Ai(c) C($c-trend-down) 正常綠色
#Jc(fe) Fw(600) C(#fff) Px(6px) Py(2px) Bdrs(4px) Bgc($c-trend-up) 特殊紅色
#Jc(fe) Fw(600) D(f) Ai(c) 黑色

['9.53', '3.99', '20.30', '24.54', '53.60', '141.00', '22.00', '58.50', '14.28', '6.14', '38.49', '114.00', '13.65', '31.00', '50.10', '13.25', '48.30', '190.50', '13.55', '5.58', '8.01', '30.95', '45.50', '15.15', '25.50', '43.70', '26.40', '8.05', '55.40', '26.30', '788.00', '36.80', '38.05', '249.50', '53.90', '15.10', '17.60', '32.45', '8.43', '95.30', '22.87', '9.30', '17.40', '63.00', '170.50', '15.80', '19.02', '47.85', '11.90', '6.65', '51.20', '7.96', '38.45', '35.30', '26.75', '56.30', '39.10', '43.80', '12.35', '4.51', '24.15', '19.25', '65.50', '21.25', '44.55', '17.80', '65.70', '20.90', '69.90', '24.25', '36.95', '29.95', '3.50', '20.65', '76.60', '15.36', '153.00', '63.80', '6.42', '34.00', '17.46', '99.70', '44.75', '9.41', '22.40', '9.86', '27.55', '46.25', '25.70', '4.18', '18.46', '307.00', '29.30', '18.58', '34.20', '95.40', '22.55', '69.60', '21.05', '46.20']
100

In [ ]:
i=0
for x in soup.find_all('span', class_=['Fw(600) Jc(fe) D(f) Ai(c) C($c-trend-up)','Fw(600) Jc(fe) D(f) Ai(c) C($c-trend-down)','Fw(600) Jc(fe) D(f) Ai(c)']):   #漲跌/漲跌幅
  if i%2==0:
    up_down.append(x.text.strip())
  else:
    Quote_change.append(x.text.strip())
  i+=1
print(up_down)
print(Quote_change)
print(len(up_down))
print(len(Quote_change))
#Fw(600) Jc(fe) D(f) Ai(c) C($c-trend-up) 正常紅色
#Fw(600) Jc(fe) D(f) Ai(c) C($c-trend-down)正常綠色
#Fw(600) Jc(fe) D(f) Ai(c) 黑色

['0.29', '0.12', '0.55', '0.68', '2.00', '5.00', '0.51', '2.90', '0.42', '0.26', '1.13', '5.50', '0.45', '0.70', '1.50', '0.40', '0.95', '12.50', '0.08', '0.15', '0.17', '1.00', '2.05', '0.70', '1.15', '0.90', '1.80', '0.14', '2.60', '0.75', '18.00', '2.20', '1.55', '11.50', '2.10', '0.15', '0.30', '0.10', '0.27', '6.70', '0.55', '0.09', '0.45', '1.00', '7.50', '0.25', '0.61', '1.10', '0.60', '0.20', '0.50', '0.17', '0.80', '1.00', '0.45', '2.90', '0.70', '1.40', '0.70', '0.12', '0.85', '0.55', '4.50', '0.55', '2.30', '0.35', '1.70', '1.90', '1.90', '0.30', '2.05', '0.60', '0.15', '0.64', '3.10', '0.43', '7.00', '4.90', '0.05', '2.20', '0.54', '4.80', '4.55', '0.25', '0.55', '0.24', '0.60', '0.30', '0.40', '0.09', '0.49', '2.00', '1.50', '0.55', '2.70', '3.30', '1.80', '2.40', '0.55', '1.15']
['2.95%', '3.10%', '2.64%', '2.70%', '3.60%', '3.42%', '2.27%', '4.72%', '2.86%', '4.42%', '2.85%', '4.60%', '3.19%', '2.21%', '2.91%', '2.93%', '2.01%', '6.16%', '0.59%', '2.62%', '2.08%', '3.13%', '4.31%', '4.42%', '4.32%', '2.02%', '6.38%', '1.71%', '4.48%', '2.77%', '2.23%', '5.64%', '3.91%', '4.41%', '3.75%', '0.98%', '1.68%', '0.31%', '3.10%', '6.57%', '2.35%', '0.96%', '2.52%', '1.61%', '4.21%', '1.56%', '3.11%', '2.25%', '4.80%', '2.92%', '0.99%', '2.09%', '2.12%', '2.75%', '1.65%', '4.90%', '1.76%', '3.10%', '5.36%', '2.73%', '3.40%', '2.78%', '6.43%', '2.52%', '4.91%', '1.93%', '2.52%', '10.00%', '2.65%', '1.22%', '5.26%', '1.96%', '4.11%', '3.01%', '3.89%', '2.72%', '4.38%', '7.13%', '0.77%', '6.08%', '3.00%', '4.59%', '9.23%', '2.59%', '2.40%', '2.38%', '2.13%', '0.64%', '1.53%', '2.20%', '2.59%', '0.65%', '5.40%', '2.88%', '8.57%', '3.34%', '8.67%', '3.33%', '2.55%', '2.43%']
100
100

In [ ]:
i=0
for x in soup.find_all('div', class_='Fxg(1) Fxs(1) Fxb(0%) Ta(end) Mend($m-table-cell-space) Mend(0):lc Miw(74px)'):  #較高/較低
  if i > 1:
    if i%2==0:
      Highest.append(x.text.strip())
    else:
      lowest.append(x.text.strip())
  i+=1
print(Highest)
print(lowest)
print(len(Highest))
print(len(lowest))

['9.77', '4.01', '20.64', '25.05', '57.40', '143.00', '22.40', '60.80', '14.62', '6.40', '39.15', '118.50', '14.05', '31.70', '51.00', '13.60', '51.00', '201.00', '13.56', '5.66', '8.06', '32.05', '47.50', '15.75', '26.50', '47.60', '27.95', '8.18', '59.80', '27.00', '803.00', '39.70', '40.00', '261.50', '55.90', '15.19', '17.90', '33.30', '8.58', '101.00', '23.21', '9.31', '17.85', '63.50', '177.50', '16.05', '19.41', '48.80', '12.10', '6.76', '54.30', '8.01', '39.90', '36.30', '27.20', '58.80', '40.05', '45.15', '13.00', '4.54', '24.85', '19.80', '69.30', '21.90', '46.80', '18.10', '67.20', '20.90', '71.50', '24.50', '39.35', '30.50', '3.64', '21.02', '79.00', '15.68', '158.50', '68.80', '6.44', '35.50', '17.80', '103.50', '49.00', '9.69', '22.90', '10.10', '28.85', '48.10', '26.10', '4.19', '18.76', '322.50', '29.40', '18.99', '34.65', '98.50', '22.80', '71.70', '21.60', '47.05']
['9.53', '3.91', '20.30', '24.50', '53.60', '137.50', '21.92', '57.80', '14.26', '5.72', '38.27', '112.50', '13.55', '30.95', '50.10', '13.10', '48.10', '189.00', '13.25', '5.52', '7.99', '30.90', '45.00', '14.90', '25.30', '41.50', '26.00', '8.03', '54.30', '26.20', '785.00', '36.80', '37.85', '248.00', '53.30', '15.06', '17.45', '32.40', '8.37', '94.10', '22.67', '9.28', '17.40', '59.40', '170.00', '15.80', '18.95', '47.55', '11.86', '6.60', '50.20', '7.94', '36.30', '34.90', '26.75', '56.30', '39.10', '43.55', '11.75', '4.43', '24.00', '19.25', '64.60', '21.15', '44.40', '17.75', '65.60', '20.20', '67.80', '24.20', '36.60', '29.80', '3.48', '20.46', '76.30', '15.25', '152.50', '63.30', '6.41', '33.85', '17.36', '98.60', '44.40', '9.37', '22.35', '9.86', '27.25', '44.80', '25.70', '4.16', '18.33', '297.00', '27.85', '18.47', '31.95', '95.00', '21.40', '67.00', '20.75', '45.20']
100
100

In [ ]:
i=0
for x in soup.find_all('div', class_='Fxg(1) Fxs(1) Fxb(0%) Ta(end) Mend($m-table-cell-space) Mend(0):lc Miw(52px)'):  #價差
  if i!=0:
    price_gap.append(x.text.strip())
  i+=1
print(price_gap)
print(len(price_gap))

['0.24', '0.10', '0.34', '0.55', '3.80', '5.50', '0.48', '3.00', '0.36', '0.68', '0.88', '6.00', '0.50', '0.75', '0.90', '0.50', '2.90', '12.00', '0.31', '0.14', '0.07', '1.15', '2.50', '0.85', '1.20', '6.10', '1.95', '0.15', '5.50', '0.80', '18.00', '2.90', '2.15', '13.50', '2.60', '0.13', '0.45', '0.90', '0.21', '6.90', '0.54', '0.03', '0.45', '4.10', '7.50', '0.25', '0.46', '1.25', '0.24', '0.16', '4.10', '0.07', '3.60', '1.40', '0.45', '2.50', '0.95', '1.60', '1.25', '0.11', '0.85', '0.55', '4.70', '0.75', '2.40', '0.35', '1.60', '0.70', '3.70', '0.30', '2.75', '0.70', '0.16', '0.56', '2.70', '0.43', '6.00', '5.50', '0.03', '1.65', '0.44', '4.90', '4.60', '0.32', '0.55', '0.24', '1.60', '3.30', '0.40', '0.03', '0.43', '25.50', '1.55', '0.52', '2.70', '3.50', '1.40', '4.70', '0.85', '1.85']
100

In [ ]:
i=0
for x in soup.find_all('div', class_='Fxg(1) Fxs(1) Fxb(0%) Ta(end) Mend($m-table-cell-space) Mend(0):lc Miw(80px)'):  #成交量
  if i!=0:
     Trading_volume.append(x.text.strip())
  i+=1
print(Trading_volume)
print(len(Trading_volume))

['659,605', '443,080', '348,054', '263,473', '230,673', '175,093', '155,627', '145,762', '137,232', '129,895', '116,359', '97,161', '89,961', '89,743', '85,234', '84,975', '82,629', '76,276', '72,935', '70,961', '67,207', '66,139', '62,586', '59,086', '59,067', '56,254', '55,337', '52,119', '51,160', '50,869', '49,412', '48,646', '48,240', '46,395', '45,374', '44,775', '42,695', '42,491', '42,234', '39,054', '36,884', '36,806', '36,544', '36,314', '36,213', '35,887', '34,885', '34,227', '34,192', '33,180', '31,849', '31,099', '30,927', '29,760', '29,698', '28,369', '28,128', '27,849', '26,745', '26,714', '26,420', '26,209', '26,185', '25,761', '25,718', '25,431', '25,063', '24,858', '24,724', '24,508', '24,316', '23,494', '23,232', '22,152', '21,764', '21,632', '21,432', '21,373', '21,054', '20,857', '20,697', '20,538', '20,484', '20,358', '20,178', '20,150', '20,100', '20,049', '19,892', '19,416', '19,073', '18,931', '18,908', '18,905', '18,803', '18,580', '18,084', '17,683', '17,670', '17,133']
100

In [ ]:
i=0
for x in soup.find_all('div', class_='Fxg(1) Fxs(1) Fxb(0%) Ta(end) Mend(0):lc Miw(88px) Mend(12px)'):  #成交量
  if i!=0:
     Transaction_amount.append(x.text.strip())
  i+=1
print(Transaction_amount)
print(len(Transaction_amount))

['63.3610', '17.5619', '70.9801', '65.0125', '127.7543', '245.1813', '34.3691', '86.1860', '19.6979', '7.8905', '44.9526', '111.6797', '12.3286', '27.9859', '42.9960', '11.3160', '40.7486', '147.7305', '9.7923', '3.9593', '5.3898', '20.6684', '28.7436', '8.9700', '15.2503', '25.4160', '14.7699', '4.2103', '28.9552', '13.4956', '391.1173', '18.3738', '18.7340', '117.0867', '24.6270', '6.7586', '7.5333', '13.9388', '3.5748', '37.8512', '8.4384', '3.4215', '6.4167', '22.3510', '62.4464', '5.6947', '6.6742', '16.4394', '4.0932', '2.2154', '16.7767', '2.4781', '11.8124', '10.5934', '7.9890', '16.2302', '11.0878', '12.2698', '3.2282', '1.1957', '6.3970', '5.0909', '17.4088', '5.5078', '11.6234', '4.5448', '16.5836', '5.1715', '17.1343', '5.9512', '9.1254', '7.0518', '0.8208', '4.5815', '16.8224', '3.3256', '33.0567', '14.0499', '1.3524', '7.1761', '3.6225', '20.6037', '9.4300', '1.9250', '4.5470', '2.0024', '5.6278', '9.3871', '5.1341', '0.8102', '3.5240', '59.0672', '5.4346', '3.5302', '6.2852', '17.8962', '4.0488', '12.1767', '3.7197', '7.8574']
100

In [ ]:
print(len(num))
print(len(price))
print(len(up_down))
print(len(Quote_change))
print(len(Highest))
print(len(lowest))
print(len(price_gap))
print(len(Trading_volume))
print(len(Transaction_amount))

100
100
100
100
100
100
100
100
100

In [ ]:
df = pd.DataFrame(data)

df.index = [str(i) for i in range(1, 101)]  #自訂索引值
df.columns = ["Stock_Number", "price", "up_down","Quote_change","Highest","lowest","price_gap","Trading_volume","Transaction_amount(100 million)"]  #自訂欄位名稱

print(df)
# 將 DataFrame 輸出為 CSV 文件
df.to_csv('data.csv', index=False)
# 將 DataFrame 輸出為 JSON 文件
df.to_json('data.json', orient='records')

    Stock_Number  price up_down Quote_change Highest lowest price_gap  \
1       00940.TW   9.53    0.29        2.95%    9.77   9.53      0.24
2      00632R.TW   3.99    0.12        3.10%    4.01   3.91      0.10
3       00929.TW  20.30    0.55        2.64%   20.64  20.30      0.34
4       00919.TW  24.54    0.68        2.70%   25.05  24.50      0.55
5        1609.TW  53.60    2.00        3.60%   57.40  53.60      3.80
..           ...    ...     ...          ...     ...    ...       ...
96       4938.TW  95.40    3.30        3.34%   98.50  95.00      3.50
97       1617.TW  22.55    1.80        8.67%   22.80  21.40      1.40
98       3013.TW  69.60    2.40        3.33%   71.70  67.00      4.70
99       6005.TW  21.05    0.55        2.55%   21.60  20.75      0.85
100      2101.TW  46.20    1.15        2.43%   47.05  45.20      1.85

    Trading_volume Transaction_amount(100 million)
1          659,605                         63.3610
2          443,080                         17.5619
3          348,054                         70.9801
4          263,473                         65.0125
5          230,673                        127.7543
..             ...                             ...
96          18,580                         17.8962
97          18,084                          4.0488
98          17,683                         12.1767
99          17,670                          3.7197
100         17,133                          7.8574

[100 rows x 9 columns]